### PR TITLE
fix version in MANIFEST

### PR DESCRIPTION
**Pull request by matthdsm**
Perhaps also find a way to keep the version numbers in sync across the repo?

### CODE REVIEW

**Comment by matthdsm** [comment]
There has to be an issue with it somewhere I think 🤔 
I'm seeing the following in my nextflow logs

```
Nov-12 09:39:36.154 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins declared=[nf-nomad@0.3.0]
Nov-12 09:39:36.156 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Nov-12 09:39:36.156 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-nomad@0.3.0]
Nov-12 09:39:36.156 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-nomad version: 0.3.0
Nov-12 09:39:36.204 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-nomad@0.1.2' resolved
Nov-12 09:39:36.204 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-nomad@0.1.2'
```

**Comment by jagedn** [comment]
Will take a look, meanwhile we can merge your PR

**Review by jagedn — APPROVED** [review]

**Comment by matthdsm** [comment]
I just checked the zip from the latest release and I can confirm the version in the manifest is correct. Perhaps it's something on my end

**Comment by abhi18av** [comment]
Hi @matthdsm , marking this as draft till you give a go ahead for the update.

The version in particular file hasn't caused issues earlier so maybe there's some `nextflow.config` of env variable file which is pointing to the wrong  version of the plugin 🤔

**Comment by matthdsm** [comment]
Hi,

I investigated a bit more, and the issue lies in the plugin somewhere.
The version is defined in 2 locations:
`$NXF_ASSETS/plugins/nf-nomad-0.3.0/classes/META-INF/MANIFEST.MF`
and
`$NXF_ASSETS/plugins/nf-nomad-0.3.0/META-INF/MANIFEST.MF`

The manifest in the `classes` dir is set to 0.1.2, whereas the other one is correct.

**Comment by abhi18av** [comment]
Thank you @matthdsm for reporting this and for the proposed fix, we have just released https://github.com/nextflow-io/nf-nomad/releases/tag/0.3.1 which should fix this issue and hopefully this version should be available upstream.

**Comment by matthdsm** [comment]
Hi Abhi,

issue still persists 
```
Dec-09 09:54:14.390 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-nomad version: 0.3.1
Dec-09 09:54:14.413 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-nomad@0.1.2' resolved
Dec-09 09:54:14.419 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-nomad@0.1.2'
Dec-09 09:54:14.867 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-nomad@0.1.2
```

**Comment by abhi18av** [comment]
Ah, I see what the issue is - the file `nf-nomad/plugins/nf-nomad/src/resources/META-INF/MANIFEST.MF` should not be there. 

I am trying to address this issue and #96 in https://github.com/nextflow-io/nf-nomad/pull/97 

Thank you for the quick turnaround and feedback @matthdsm ! 💯

**Pull request closed without merging**
