### PR TITLE
Mount volume spec

### LINKED ISSUE #13: Allow storage config using nomad `volume` blocks
While docker volumes is a quick way to prototype adding storage to a job/task it is not considered best practice in nomad. Since it is very driver specific approach and bypasses any native storage (Volume) handling in Nomad. Also most production clusters will lock down mounting volumes this way for security reasons. So we should find a user friendly way to do this using the nomad `volume` block.

_Originally posted by @tomiles in https://github.com/nextflow-io/nf-nomad/pull/12#discussion_r1493728335_

### PR DESCRIPTION
**Pull request by jagedn**
close #13 

This PR implements a new `volume` config where the user can specify the `type` and the `name`of the volume

Valid types are `host`, `csi` and `docker` and the service create a JobSpec mounting it 

`dockerVolume` is deprecated so the user must to use new configuration if want to mount a docker volume

We've agreed only a volume is required, at least by the moment

### CODE REVIEW

**Review by abhi18av — APPROVED** [review]
Thanks dear Jorge for finalizing this.

As discussed in our dev sync, I think we can now start the next phase of implementing other Nomad Job specs and map the Nextflow directives over them.


Excited to test a couple more pipelines with these changes! 🤩

**Comment by abhi18av** [comment]
Adding some context here regarding the current syntax for specifying the volume 


```groovy

nomad {
    client {
        address = "http://NOMAD_IP:4646"
        token = ""
    }

    jobs {
       datacenters = "sun-nomadlab"
       volume = [ type: "csi", name: "csi-volume-name" ]
    }
}

```

**Comment by jagedn** [comment]
Once we have the "asciidoctor/gh-pages/user guide" ready it will be a "requirement" to document this kind of stuff on it

**Comment by abhi18av** [comment]
@jagedn , that makes sense.

Just adding a thought for future reference, what if we want to allow the mounting multiple volumes within the same job?


In that case, wouldn't it be easier to have Map oriented syntax, which can compose multiple volume-maps into an array specification. As shown below


```nextflow
    jobs {
       datacenters = "sun-nomadlab"
       volume = [
                  [
                     env: "csi"  // CSI volume type
                     name: "csi-volume-name" 
                  ],
                  [
                     env: "host"  // HOST volume type
                     name: "host-volume-name" 
                  ],
     ]
    }
``` 


This way we would keep the possibility of (multiple) HOST + CSI volumes into the same job definition, what do you think? 🤔

**Pull request merged**
