### PR TITLE
add Constraints (Node and Attr)

### PR DESCRIPTION
**Pull request by jagedn**
Allow to add constraints in Job or Task

Current PR implements Node constraints and a partial list of Attr constraints

### CODE REVIEW

**Comment by jagedn** [comment]
Implemented a `raw` constraint (in node and attr) so users can add custom/specific constraints, for example:

```
constraints{
   attr {
       raw 'platform.aws.instance-type', '=', 'm4.xlarge'
   }
}
```

**Comment by abhi18av** [comment]
> Implemented a raw constraint (in node and attr) so users can add custom/specific constraints, for example:


Ah, this is good! Provides an escape hatch for things we can't foresee for now.


But, as of https://github.com/nextflow-io/nf-nomad/pull/66/commits/08b82b1d89f8a8ac79d5cfff9f1e949df27c54b9 is the following working for you with the intended effect? 

```
 ./run-all.sh --skiplocal --build --nfsun --demo

```


On the Nomad portal, I can't see any of the constraints/attr show up 

image

**Comment by jagedn** [comment]
the nextflow.config has 2 typos 

```
constraints: {    // wrong, is an assignment "constraints = {"
            attr {
                unique = [hostName:'nomad02']    // typo, hostname is lowercase
            }
        }
```

once fixed the constraint is applied

imagen

**Review by abhi18av — APPROVED** [review]
Great! 

I can confirm, that this is working nicely with the our pure `fusionfs` based `sun-nomadlab` cluster 🎉

**Pull request merged**
