### PR TITLE
Allow 1 restart per task

### PR DESCRIPTION
**Pull request by matthdsm**
This should fix a concurrency issue with the CSI driver 
cfr https://github.com/ceph/ceph-csi/issues/3511 and https://github.com/hashicorp/nomad/issues/15197

### CODE REVIEW

**Comment by abhi18av** [comment]
@matthdsm , would this trigger a `nomad-native` retry or is this expecting Nextflow to trigger this? 

As of now, we have a model of `1 nextflow task -> 1 nomad job` and therefore, error at nomad job level reflects error at nextflow level. 

How `nomad-native` retries would interact with the overall setup needs to be tested.

**Comment by abhi18av** [comment]
> If I'm not wrong, before to have this constants we're using the default value (3) and Nextflow wait correctly for the completion of a failed job, so maybe can be a good idea to use 1 as default

I think that 3 is the default for these attempts https://github.com/nextflow-io/nf-nomad/pull/82#issuecomment-2315371597 


@jagedn , do you think its worth exposing the closure and including other fields like `delay` , `interval` etc?

**Review by jagedn — APPROVED** [review]

**Comment by abhi18av** [comment]
Okay, merging this and tagging this realease as `0.2.0-edge3` to release a build

**Comment by jagedn** [comment]
> 
> @jagedn , do you think its worth exposing the closure and including other fields like `delay` , `interval` etc?

maybe we can implement all of them when required

**Pull request merged**
